import { Hono } from 'hono'; import type { Context } from 'hono'; import { deleteCookie,getCookie,setCookie } from 'hono/cookie'; import { z } from 'zod'; import type { AppEnv,CmsUser } from '../types'; import { fail,ok } from '../lib/response'; import { hashPassword,hashToken,randomToken,verifyPassword } from '../lib/crypto'; import { requireAdmin,requireAuth } from '../middleware/auth';
const credentials=z.object({email:z.string().trim().email().max(254).transform(v=>v.toLowerCase()),password:z.string().min(12).max(128),name:z.string().trim().min(2).max(100).optional(),invite:z.string().min(32).optional()});
const cookie=(c:Context<AppEnv>)=>({httpOnly:true,secure:c.env.ENVIRONMENT!=='local',sameSite:'Strict' as const,path:'/api',maxAge:60*60*24*7});
async function createSession(c:Context<AppEnv>,userId:number){const token=randomToken(),csrf=randomToken();await c.env.DB.prepare('INSERT INTO sessions (id,user_id,token_hash,csrf_token_hash,expires_at) VALUES (?,?,?,?,?)').bind(crypto.randomUUID(),userId,await hashToken(token),await hashToken(csrf),new Date(Date.now()+604800000).toISOString()).run();setCookie(c,'dc_session',token,cookie(c));return csrf;}
export const auth=new Hono<AppEnv>()
.post('/bootstrap',async(c)=>{if(c.req.header('x-bootstrap-token')!==c.env.CMS_BOOTSTRAP_TOKEN)return fail(c,'FORBIDDEN','Inicialização não autorizada.',403);const total=await c.env.DB.prepare('SELECT COUNT(*) AS total FROM users').first<{total:number}>();if((total?.total??0)>0)return fail(c,'ALREADY_INITIALIZED','O administrador inicial já existe.',409);const parsed=credentials.required({name:true}).safeParse(await c.req.json());if(!parsed.success)return fail(c,'VALIDATION_ERROR','Use nome, e-mail válido e senha com 12 caracteres.',400);const result=await c.env.DB.prepare("INSERT INTO users (email,name,password_hash,role) VALUES (?,?,?,'admin')").bind(parsed.data.email,parsed.data.name,await hashPassword(parsed.data.password)).run();return ok(c,{message:'Administrador criado.',userId:result.meta.last_row_id},201);})
.post('/login',async(c)=>{const parsed=credentials.pick({email:true,password:true}).safeParse(await c.req.json());if(!parsed.success)return fail(c,'INVALID_CREDENTIALS','E-mail ou senha inválidos.',401);const user=await c.env.DB.prepare("SELECT id,email,name,password_hash AS passwordHash,role FROM users WHERE email=? AND status='active' LIMIT 1").bind(parsed.data.email).first<CmsUser&{passwordHash:string}>();if(!user||!await verifyPassword(parsed.data.password,user.passwordHash))return fail(c,'INVALID_CREDENTIALS','E-mail ou senha inválidos.',401);const csrf=await createSession(c,user.id);return ok(c,{user:{id:user.id,email:user.email,name:user.name,role:user.role},csrf});})
.get('/session',requireAuth,async(c)=>{const token=getCookie(c,'dc_session')!;const csrf=randomToken();await c.env.DB.prepare('UPDATE sessions SET csrf_token_hash=? WHERE token_hash=?').bind(await hashToken(csrf),await hashToken(token)).run();return ok(c,{user:c.get('user'),csrf});})
.post('/logout',requireAuth,async(c)=>{const token=getCookie(c,'dc_session');if(token)await c.env.DB.prepare('DELETE FROM sessions WHERE token_hash=?').bind(await hashToken(token)).run();deleteCookie(c,'dc_session',{path:'/api'});return ok(c,{message:'Sessão encerrada.'});})
.post('/invite',requireAuth,requireAdmin,async(c)=>{const parsed=z.object({email:z.string().email(),role:z.enum(['admin','editor']).default('editor')}).safeParse(await c.req.json());if(!parsed.success)return fail(c,'VALIDATION_ERROR','Convite inválido.',400);const token=randomToken();await c.env.DB.prepare('INSERT INTO invitations (email,role,token_hash,invited_by,expires_at) VALUES (?,?,?,?,?)').bind(parsed.data.email.toLowerCase(),parsed.data.role,await hashToken(token),c.get('user').id,new Date(Date.now()+172800000).toISOString()).run();return ok(c,{inviteToken:token,expiresInHours:48},201);})
.post('/register',async(c)=>{const parsed=credentials.required({name:true,invite:true}).safeParse(await c.req.json());if(!parsed.success)return fail(c,'VALIDATION_ERROR','Dados de cadastro inválidos.',400);const invitation=await c.env.DB.prepare('SELECT id,email,role FROM invitations WHERE token_hash=? AND used_at IS NULL AND expires_at>CURRENT_TIMESTAMP LIMIT 1').bind(await hashToken(parsed.data.invite)).first<{id:number,email:string,role:'admin'|'editor'}>();if(!invitation||invitation.email!==parsed.data.email)return fail(c,'INVITE_INVALID','Convite inválido ou expirado.',403);const passwordHash=await hashPassword(parsed.data.password);const batch=await c.env.DB.batch([c.env.DB.prepare('INSERT INTO users (email,name,password_hash,role) VALUES (?,?,?,?)').bind(parsed.data.email,parsed.data.name,passwordHash,invitation.role),c.env.DB.prepare('UPDATE invitations SET used_at=CURRENT_TIMESTAMP WHERE id=?').bind(invitation.id)]);return ok(c,{message:'Conta criada.',userId:batch[0]?.meta.last_row_id},201);});
